import { ReservationStatus } from "@/src/types/my-reservations";

const mockReservationData = {
  pages: [
    {
      cursorId: 1,
      totalCount: 3,
      reservations: [
        {
          id: 1,
          teamId: "team1",
          userId: 101,
          activity: {
            bannerImageUrl: "/images/test_img.png",
            title: "서울 도심 투어",
            id: 201,
          },
          scheduleId: 301,
          status: "confirmed" as ReservationStatus,
          reviewSubmitted: false,
          totalPrice: 50000,
          headCount: 2,
          date: "2025-02-15",
          startTime: "10:00",
          endTime: "13:00",
          createdAt: "2025-01-20T09:00:00Z",
          updatedAt: "2025-01-20T09:00:00Z",
        },
        {
          id: 2,
          teamId: "team2",
          userId: 102,
          activity: {
            bannerImageUrl: "/images/test_img.png",
            title: "한강 자전거 투어",
            id: 202,
          },
          scheduleId: 302,
          status: "pending" as ReservationStatus,
          reviewSubmitted: false,
          totalPrice: 60000,
          headCount: 3,
          date: "2025-03-01",
          startTime: "14:00",
          endTime: "17:00",
          createdAt: "2025-01-25T10:30:00Z",
          updatedAt: "2025-01-25T10:30:00Z",
        },
        {
          id: 3,
          teamId: "team3",
          userId: 103,
          activity: {
            bannerImageUrl: "/images/test_img.png",
            title: "남산 야경 투어",
            id: 203,
          },
          scheduleId: 303,
          status: "completed" as ReservationStatus,
          reviewSubmitted: true,
          totalPrice: 80000,
          headCount: 4,
          date: "2025-01-10",
          startTime: "19:00",
          endTime: "22:00",
          createdAt: "2024-12-20T14:15:00Z",
          updatedAt: "2025-01-11T10:00:00Z",
        },
        {
          id: 4,
          teamId: "team4",
          userId: 106,
          activity: {
            bannerImageUrl: "/images/test_img.png",
            title: "남산 야경 투어",
            id: 204,
          },
          scheduleId: 304,
          status: "completed" as ReservationStatus,
          reviewSubmitted: true,
          totalPrice: 80000,
          headCount: 4,
          date: "2025-01-10",
          startTime: "19:00",
          endTime: "22:00",
          createdAt: "2024-12-20T14:15:00Z",
          updatedAt: "2025-01-11T10:00:00Z",
        },
      ],
    },
  ],
};

export default mockReservationData;
